import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'sonner';
import "./globals.css";
import Providers from "@/providers/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SecondHand Mart",
  description: "Generated by SecondHand Mart",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.className} antialiased`}
        >

          <Toaster
            position="top-right"
            duration={1000}
            toastOptions={{
              style: {
                backgroundColor: '#ff6f00',
                color: '#ffffff',
                borderRadius: '8px',
              },
            }}
          />
          {children}
        </body>
      </html>
    </Providers>
  );
}
